### ISSUE TITLE
ヘッダーでグローバル変数を宣言しないようにする。

### ISSUE THREAD

**Issue by s-xix98** [uminomae/refactor_tetris#2]
https://github.com/uminomae/refactor_tetris/blob/9b58e5402e27a9a1a076ebccbc1bb8f4ba6781ab/type.h#L3

ヘッダーでグローバル変数を宣言するのではなく、
.c ファイルに書いてください。

ヘッダーには `extern const t_tetrimino type_tetrimino[7];`
と書いとく感じで。

**Comment by uminomae** [comment]
修正しました。

なお、使っているのは type.hが適用されている init_and_begin.cだけです。
commit 4b79c01519126502d45fc4b480c9f93f312b4ac1 (HEAD -> use-malloc, origin/use-malloc)
