### ISSUE TITLE
's' にも define を使用する。

### ISSUE THREAD

**Issue by s-xix98** [uminomae/refactor_tetris#3]
https://github.com/uminomae/refactor_tetris/blob/f71df18ee512de489111bceafe8a0ac0a96b5b78/run.c#L40

**Comment by uminomae** [comment]
commit 6d56939525510f313d5ae8c0f17a8370bac02ca3 (HEAD -> use-malloc, origin/use-malloc)

**Comment by uminomae** [comment]
↑.h修正したやつと同時なっちゃいました。上の方だけ。

**Comment by s-xix98** [comment]
関数名なんかバグってませんか？w
`move_by_key_caDROP_KEYe`

**Comment by uminomae** [comment]
修正しました笑

commit 4b79c01519126502d45fc4b480c9f93f312b4ac1 (HEAD -> use-malloc, origin/use-malloc)

**Comment by uminomae** [comment]
externと同時でコミットなってます
